Remove unnecessary peerDependencies
jaydenseric/apollo-upload-client pull request #235
Opened 2020-11-05 08:57 UTC by PowerKiKi

Because @apollo/client is declared as a hard dependencies, and it
itself declare its own dependencies, there is no need to match them here,
since we don't reference any of those packages in our code.

2020-11-05 22:18 UTC, jaydenseric reviewed
I totally agree, and your PR is how I originally had it. The thing is, I had users complain that Yarn “Berry” PnP strict mode apparently required the peer dependencies to be declared in this package, see:

- https://github.com/jaydenseric/apollo-upload-client/pull/196#issuecomment-650496294
- https://github.com/jaydenseric/apollo-upload-client/pull/175#issuecomment-658118311

What do you think about it? I don't use Yarn, so I'm not sure if the situation has changed and it's safe to remove the extra peer dependencies again.

2020-11-06 02:00 UTC, PowerKiKi commented
Unfortunately this still happens with yarn 2.3.3. I was not aware of this behavior, but was able to reproduce it by publishing myself a test version of this lib and running:

```sh
rm -rf /tmp/test-peer && mkdir /tmp/test-peer && cd /tmp/test-peer && yarn set version berry && yarn --version && yarn init && yarn add apollo-upload-client-test-without-peer @apollo/client graphql
```

This would lead to the following output:

```
Resolving berry to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
Saving it into /tmp/test-peer/.yarn/releases/yarn-berry.cjs...
Updating /tmp/test-peer/.yarnrc.yml...
Done!
2.3.3
{
  name: 'test-peer'
}
➤ YN0000: ┌ Resolution step
➤ YN0002: │ apollo-upload-client-test-without-peer@npm:14.1.2 doesn't provide graphql@^14.0.0 || ^15.0.0 requested by @apollo/client@npm:3.2.5
➤ YN0000: └ Completed in 2s 425ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ regenerator-runtime@npm:0.13.7 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ symbol-observable@npm:2.0.3 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ ts-invariant@npm:0.4.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ tslib@npm:1.14.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zen-observable@npm:0.8.15 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 2s 688ms
```

Where we can see that yarn complains about `graphql`.  This is clearly documented in https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency, and matching the peer in this package is indeed one of the solution. That sound like huge burden on lib maintainers...

Anyway, since apollo 3.2.1 subscriptions-transport-ws is [also optional](https://github.com/apollographql/apollo-client/commit/99d3fef9922755f57f3cc7bd6f1f64090c1db06d). So the only peer we need to match is graphql itself.

I updated my PR accordingly.

2020-11-06 02:59 UTC, jaydenseric commented
Should we also mark `subscriptions-transport-ws` as optional, instead of removing it? Have you tested Yarn installs ok without `subscriptions-transport-ws` in peer dependencies?

2020-11-06 03:09 UTC, PowerKiKi commented
There is no need to mention `subscriptions-transport-ws` at all in our package, because it already is marked as optional in apollo. This variant is the second solution suggested [in the docs](https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency).

I also tested it out with my test package. Right now if you run the command mentionned in 
https://github.com/jaydenseric/apollo-upload-client/pull/235#issuecomment-722760495, you'll get the latest version of my test package which is exactly this PR.

This would get you this correct output:

```
Resolving berry to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
Saving it into /tmp/test-peer/.yarn/releases/yarn-berry.cjs...
Updating /tmp/test-peer/.yarnrc.yml...
Done!
2.3.3
{
  name: 'test-peer'
}
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 730ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ regenerator-runtime@npm:0.13.7 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ symbol-observable@npm:2.0.3 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ ts-invariant@npm:0.4.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ tslib@npm:1.14.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zen-observable@npm:0.8.15 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 0s 970ms
```

Another proof that it is not necessary is the fact that `react` also is an optional peer in `@apollo/client`. But it was never mentioned in our package.json. And it never caused any issue.

2020-11-06 03:13 UTC, jaydenseric requested changes
We need to add a `changelog.md` entry that includes this PR link.

2020-11-06 03:13 UTC, jaydenseric commented on package.json
> +    "graphql": "^14.0.0 || ^15.0.0"
Can we please revert this syntax change?

```suggestion
    "graphql": "14 - 15"
```

2020-11-06 03:18 UTC, PowerKiKi commented
done in a squashed commit

2020-11-08 01:26 UTC, jaydenseric approved these changes
Thanks for your work :)

2020-11-08 01:27 UTC, merged

2020-11-08 02:42 UTC, jaydenseric commented
Published in [`apollo-upload-client@14.1.3`](https://github.com/jaydenseric/apollo-upload-client/releases/tag/v14.1.3) 🚀